
// FETCH_AUTHORIZATION
export const FETCH_LOGIN_USER = 'FETCH_LOGIN_USER';
export const FETCH_LOGOUT_USER = 'FETCH_LOGOUT_USER';

// FETCH_USER
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const UPDATE_USER_NOTE_LIST = 'UPDATE_USER_NOTE_LIST';
export const UPDATE_USER_LABEL_LIST = 'UPDATE_USER_LABEL_LIST';
export const UPDATE_USER_COLOR_LIST = 'UPDATE_USER_COLOR_LIST';


// FETCH_COLORS
export const FETCH_COLORS_REQUEST = 'FETCH_COLORS_REQUEST';
export const FETCH_COLORS_SUCCESS = 'FETCH_COLORS_SUCCESS';
export const FETCH_COLORS_FAILURE = 'FETCH_COLORS_FAILURE';

// FETCH_NOTES
export const FETCH_NOTES_REQUEST = 'FETCH_NOTES_REQUEST';
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
export const FETCH_NOTES_FAILURE = 'FETCH_NOTES_FAILURE';

// export const NOTE_SAVED = 'NOTE_SAVED';

